### ISSUE TITLE
grunt-bable's compile is terrible slowly

### ISSUE THREAD

**Issue by ghjagus** [babel/grunt-babel#57]
recently, i have used grunt-beble to transform es6 to es5 in my project. it worked but i found that the compile time is so long.it took 6~7 seconds to compile one es6 file which only has one line code in it.

here's my npms
"devDependencies": {
    "babel-preset-es2015": "^6.1.4",
    "grunt-babel": "^6.0.0",
    "time-grunt": "^1.2.2"
  }

my gruntfile:
grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        babel: {
            test: {
                options: {
                    presets: ['es2015'],
                    compact: false
                },
                files: [{
                    expand: true,
                    cwd: 'test',
                    src: ['*.es6'],
                    dest: 'dist',
                    ext: ".js"
                }]
            }
        }
    });

and the es6 file's contents
let a = 1;
let b = 2;

the compile result: 
λ grunt
Running "babel:test" (babel) task

Done, without errors.

Execution Time (2015-11-12 03:06:05 UTC)
loading tasks  1s  ██████████████████████████ 13%
babel:test     7s  ████████████████████████████████████████████████████████████
Total 8s

i have tried to find the reason in google,but no one mentioned this situation。
has anybody comes my question? 
much thanks!

**Comment by ghjagus** [comment]
today i update my nodejs to v5.1.0, and the question is solved.

**Comment by lasfin** [comment]
@ghjagus Could you tell how compile speed has changed?

**Comment by ghjagus** [comment]
@lasfin i don't know. i just update the nodejs to v5.1.0 
and the compiling time becomes normal

**Comment by jmmendivil** [comment]
the update didn't fix the issue on windows 7

node 5.1.0
npm 3.3.12

package.json:
```json
  "devDependencies": {
    "babel-preset-es2015": "^6.1.18",
    "grunt": "^0.4.5",
    "grunt-babel": "^6.0.0",
    "time-grunt": "^1.2.2"
  }
```
foo.js:
```js
let foo = (f='foo') => f
console.log(foo())
```
Gruntfile.js
```js
module.exports = function (grunt) {
  require('time-grunt')(grunt)

  grunt.initConfig({
    babel: {
      options: {
        sourceMap: true,
        presets: ['es2015']
      },
      dist: {
        files: { 'foo_es5.js': 'foo.js' }
      }
    }
  })

  grunt.loadNpmTasks('grunt-babel')

  grunt.registerTask('default', ['babel'])
}
```
```
$ grunt
Running "babel:dist" (babel) task

Done, without errors.


Execution Time (2015-11-27 03:29:36 UTC)
loading tasks   1.2s  ██████████████ 10%
babel:dist     10.5s  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 90%
Total 11.7s
```

**Comment by realph** [comment]
Having this same issue. Updating my version of node didn't fix it. Anyone else having this issue?

**Comment by justinledouxweb** [comment]
Same here. It is slower than all other tasks put together.

```bash
Execution Time (2016-02-15 19:37:53 UTC)
loading tasks  581ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 12%
compass:dist    1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 25%
cssmin:target  209ms  ▇▇▇▇▇▇▇▇ 4%
babel:dist      2.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 56%
uglify:target   88ms  ▇▇▇▇ 2%
Total 4.7s
```

**Comment by sbstnmsch** [comment]
Hey,
do a `npm i time-require` and require that at the top of your `Gruntfile.js`
```
require('time-require');
```
... and you will notice that it's caused by loading the `babel-preset-es2015`:

```
...
 98  babel-traverse (node_modules/babel-preset-es2...te/node_modules/babel-traverse/lib/index.js)  452ms  ▇▇▇▇▇▇ 6%
 99  babel-template (node_modules/babel-preset-es2...js/node_modules/babel-template/lib/index.js)  479ms  ▇▇▇▇▇▇ 6%
100  babel-plugin-transform-es2015-modules-commonj...nsform-es2015-modules-commonjs/lib/index.js)  517ms  ▇▇▇▇▇▇▇ 7%
101  /Users/smi/git/project/fro...(node_modules/babel-preset-es2015/index.js)    3.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 50%
102  ./path (node_modules/babel-preset-es2015/node...de_modules/babel-traverse/lib/path/index.js)  158ms  ▇▇ 2%
103  ./context (node_modules/babel-preset-es2015/n.../node_modules/babel-traverse/lib/context.js)  161ms  ▇▇ 2%
104  babel-traverse (node_modules/babel-preset-es2...or/node_modules/babel-traverse/lib/index.js)  181ms  ▇▇▇ 2%
105  ./converters (node_modules/babel-preset-es201.../node_modules/babel-types/lib/converters.js)  202ms  ▇▇▇ 3%
106  babel-types (node_modules/babel-preset-es2015...rator/node_modules/babel-types/lib/index.js)  339ms  ▇▇▇▇ 4%
107  ./visit (node_modules/babel-preset-es2015/nod...l-plugin-transform-regenerator/lib/visit.js)  350ms  ▇▇▇▇▇ 5%
Total require(): 12134
Total time: 7.8s
...
```

**Comment by hzoo** [comment]
We recommend using npm dedupe or npm 3 for babel 6

**Comment by sbstnmsch** [comment]
Node5 with npm 3 is indeed faster:

7,8s -> 5.7s

**Comment by sindresorhus** [comment]
You could use https://github.com/tschaub/grunt-newer for caching.

This is an issue with Babel itself, not this plugin specifically, so please continue this in https://phabricator.babeljs.io/

**Comment by ohjames** [comment]
I found that I had to use "nospawn" on my watch task to ensure the same babel instance is reused and "grunt-newer" to ensure only the changed files are compiled. However grunt-mocha-test doesn't like nospawn, so I ended up having to split my watch task in two and use grunt-concurrent to run both watches at the same time. Now I'm down from a 4.1 second delay after each compile to a 0.1 second delay.
